### PR TITLE
Fixes memory leak when decrypting scuttlebutt incoming messages

### LINKED ISSUE #205: Periodic sodium OutOfMemory exception when consuming scuttlebutt streams
When consuming a scuttlebutt stream, there are periodic sodium `OutOfMemory` exception errors while decrypting the messages received as responses from the server for random messages received:

```
2019-04-02 09:37:20.086+0000 ERROR [localhost:8008] Sodium.sodium_malloc failed allocating 24
java.lang.OutOfMemoryError: Sodium.sodium_malloc failed allocating 24
	at net.consensys.cava.crypto.sodium.Sodium.malloc(Sodium.java:224)
	at net.consensys.cava.crypto.sodium.Sodium.dup(Sodium.java:262)
	at net.consensys.cava.crypto.sodium.Sodium.dup(Sodium.java:273)
	at net.consensys.cava.crypto.sodium.SecretBox$Nonce.fromBytes(SecretBox.java:230)
	at net.consensys.cava.crypto.sodium.SecretBox$Nonce.fromBytes(SecretBox.java:213)
	at net.consensys.cava.scuttlebutt.handshake.SecureScuttlebuttStream.decryptMessage(SecureScuttlebuttStream.java:107)
	at net.consensys.cava.scuttlebutt.handshake.SecureScuttlebuttStream.decrypt(SecureScuttlebuttStream.java:85)
	at net.consensys.cava.scuttlebutt.handshake.SecureScuttlebuttStream.readFromServer(SecureScuttlebuttStream.java:53)
	at net.consensys.cava.scuttlebutt.handshake.vertx.SecureScuttlebuttVertxClient$NetSocketClientHandler.handle(SecureScuttlebuttVertxClient.java:98)
	at io.vertx.core.net.impl.NetSocketImpl$DataMessageHandler.handle(NetSocketImpl.java:392)
	at io.vertx.core.streams.impl.InboundBuffer.handleEvent(InboundBuffer.java:225)
	at io.vertx.core.streams.impl.InboundBuffer.write(InboundBuffer.java:123)
	at io.vertx.core.net.impl.NetSocketImpl.handleMessage(NetSocketImpl.java:370)
	at io.vertx.core.net.impl.ConnectionBase.handleRead(ConnectionBase.java:386)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:320)
	at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:43)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:188)
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:174)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

Steps to reproduce:

1. Check out the branch underlying https://github.com/ConsenSys/cava/pull/202/files
2. Modify the `postMessageTest` test in the `PatchworkIntegrationText` file in the mux test package to post 20,000 messages by changing the for loop to iterate more and run the test. I'm not sure the minimum number of items in a stream required to make the error happen.
3. Run the `streamTest` test in the `PatchworkIntegrationTest` file in the mux package.
4. Observe the above error is occasionally output in the log.

### PR DESCRIPTION
**Pull request by Happy0**
I believe this changes fixes #205 .

I think this was happening because the underlying JNI `Pointer` for the `header` and `body` nonces weren't being freed until the garbage collector destroyed the objects which no longer had any references. Until the garbage collector destroyed them, the lib sodium `malloc` would periodically fail because there wasn't enough memory available to malloc - but once the garbage collector called `destroy` on the objects memory became free to allocate again, and the decryption would start succeeding again.

Note: this is just a theory from reading the code (i'm not sure how I'd test it empirically) but the changes appear to stop the error happening.

This change also means that if the decryption fails due to a lib sodium error, a `StreamException` will be thrown and the underlying socket (scuttlebutt connection) will be closed.

### CODE REVIEW

File: crypto/src/main/java/net/consensys/cava/crypto/sodium/Sodium.java [hunk 1]
```diff
@@ -271,6 +271,7 @@ static Pointer dup(byte[] bytes) {
 
   static <T> T dup(byte[] bytes, BiFunction<Pointer, Integer, T> ctr) {
     Pointer ptr = Sodium.dup(bytes);
+
```
Comment (atoulme) [inline crypto/src/main/java/net/consensys/cava/crypto/sodium/Sodium.java]: extra blank line

File: scuttlebutt-handshake/src/main/java/net/consensys/cava/scuttlebutt/handshake/SecureScuttlebuttStream.java [hunk 2]
```diff
@@ -100,29 +100,38 @@ private Bytes decrypt(Bytes message, SecretBox.Key key, MutableBytes nonce, bool
...
+        if (decryptedBody == null) {
+          throw new StreamException("Failed to decrypt message");
+        }
+        nonce.increment().increment();
+
+        return decryptedBody;
+
+      }
+    } catch (Exception e) {
+      throw new StreamException(e.getMessage());
```
Comment (atoulme) [inline scuttlebutt-handshake/src/main/java/net/consensys/cava/scuttlebutt/handshake/SecureScuttlebuttStream.java]: Can we be more specific - Exception is very broad.
Also can we throw StreamException(e) so we get the whole stacktrace?

File: crypto/src/main/java/net/consensys/cava/crypto/sodium/SecretBox.java [hunk 3]
```diff
@@ -193,7 +193,7 @@ public Bytes bytes() {
   /**
    * A SecretBox nonce.
    */
-  public static final class Nonce {
+  public static final class Nonce implements AutoCloseable {
```
Comment (cleishm) [inline crypto/src/main/java/net/consensys/cava/crypto/sodium/SecretBox.java]: I'm not sure I agree with making a Nonce "auto closeable". It's not a resource, so it feels odd to treat it like one. We could certainly make it implement `Destroyable`, just like the secret keys.

However, whatever we do, it must be applied consistently across all cava-sodium types.

Comment (Happy0) [reply crypto/src/main/java/net/consensys/cava/crypto/sodium/SecretBox.java]: @cleishm - I see where you're coming from. I've pushed a new commit to this PR to implement Destroyable instead.

There's currently a couple of other classes (below) that implement `AutoCloseable` that aren't 'resources' (like sockets) but on searching, it looks like the majority implement `Destroyable` like you suggested so I'll follow that convention.

```
public final class AES256GCM implements AutoCloseable {
```
```
public final class Box implements AutoCloseable {
```
Perhaps these can be made to implement 'destroyable' also in a separate PR instead.

Comment (atoulme) [reply crypto/src/main/java/net/consensys/cava/crypto/sodium/SecretBox.java]: It's a different flow. You open a secret box and close it - you don't destroy it. It's more the pointers of the keys and nonces generated along the way we need to clean up.
